# 1단계: build stage
FROM node:20 AS builder

WORKDIR /frontend
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

# 2단계: serve stage
FROM nginx:alpine

# Nginx 기본 index.html 서빙 위치
COPY --from=builder /frontend/build /usr/share/nginx/html

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
