FROM python:3.12

WORKDIR /recommend

COPY requirements.txt .
RUN pip install --upgrade pip
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

RUN apt-get update && apt-get install -y netcat-openbsd
ENTRYPOINT ["sh", "entrypoint.sh"]
